import Head from "next/head";
import conectarDB from "@/lib/dbConnect";
import Movie from "@/models/Movie";
import Link from "next/link";

export default function Home({movies}) {
    console.log(movies)

  return (
    <div>
      <Head>  
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      
      <main className="container">
        <h1 className="text-center">Movies</h1>

{/* Botón para ir a la página de agregar pelis */}
        <Link href="/new">
        <div className="btn btn-primary w-100 my-2">
          Agregar una peli
        </div>
        </Link>

        {
          movies.map(({_id, title, plot}) => (

            <div className="card mb-2" key={_id}>

              <div className="card-body">
                
                {/* Título de la peli */}
                <div className="h5 text-uppercase"> {title}</div>

                {/* Descripción de la peli */}
                <p className="fw-light">{plot}</p>


                {/* Botón para ir a la info de cada peli */}
                <Link href={`/${_id}`}>
                   <div className="btn btn-success btn-sm">Más info...</div>
                </Link>


              </div>
            </div>
          ))
        }
      </main>
        
      
    </div>
  )
}


export async function getServerSideProps(){
  try {
      await conectarDB()

      const res = await Movie.find({})

      const movies = res.map(doc => {
        const movie = doc.toObject()
        movie._id = `${movie._id}`
        return movie 
      })

     // console.log(res)

      return { props: { movies }  }
  } catch (error) {
    console.log(error)
  }
} 
